name: Clippy On-Command Benchmarking
on:
  issue_comment:
jobs:
  # For the commands on issues
  issue_commented:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    name: $REPO:$BRANCH
    steps:
      - name: Set Environment
        run: echo "BRANCH=$(echo ${{ github.event.comment.body }} | cut -d ':' -f 2 | cut -d '@' -f 1)" >> $GITHUB_ENV && echo "REPO=$(echo ${{ github.event.comment.body }} | cut -d ':' -f 1)" >> $GITHUB_ENV
      - name: Pull & Build Clippy Fork
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          path: rust-clippy
          ref: ${{ env.BRANCH }}
          # Add the posibility of a body after a '@'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cd rust-clippy && cargo build --release && cd ..
      
      - name: Pull & Build rustc-perf
        uses: actions/checkout@v4
        with:
          repository: 'blyxyas/rustc-perf' # Replace this when rustc-perf#1724 gets merged
          path: rustc-perf
          ref: clippy-timer

      - run: cd rustc-perf && cargo build --release && cd ..
      
      - name: Run rustc-perf
        run: find . -maxdepth 2 -type d -ls && rustc-perf/target/release/collector bench_local +nightly --profiles Clippy --clippy rust-clippy/target/release/cargo-clippy
