name: Weekly Clippy Benchmark
on:
  schedule:
    - cron: '0 0 * * */5'
  workflow_dispatch:

jobs:
  build_clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull & Build Clippy
        uses: actions/checkout@v4
        with:
          repository: 'rust-lang/rust-clippy'
          path: rust-clippy
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cd rust-clippy && cargo build --release && cd ..
      
      - name: Pull & Build rustc-perf
        uses: actions/checkout@v4
        with:
          repository: 'blyxyas/rustc-perf' # Replace this when rustc-perf#1724 gets merged
          path: rustc-perf
          ref: clippy-timer

      - run: cd rustc-perf && cargo build --release
      
      - name: Run rustc-perf
        run: pwd && ls && target/release/collector bench_local +nightly --profiles Clippy --clippy ../rust-clippy/target/release/cargo-clippy
